### PR TITLE
Hopefully fix Android build, fixes #2

### LINKED ISSUE #2: Build error on Android
```
/sdcard/dev/cpp/Bedrock++/lib/RakNet/src/FileList.cc:24:10: fatal error: 'sys/io.h' file
      not found
#include <sys/io.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [lib/RakNet/CMakeFiles/RakNetStatic.dir/build.make:567: lib/RakNet/CMakeFiles/RakNetStatic.dir/src/FileList.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:88: lib/RakNet/CMakeFiles/RakNetStatic.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

This also happens with the original RakNet library, could probably do with some checks.

### PR DESCRIPTION
**Pull request by lukeeey**
This works on Termux using cmake

### CODE REVIEW

**Comment by lukeeey** [comment]
This works on Termux with cmake at least. Needs testing with the NDK.

**Comment by mhsjlw** [comment]
Let me make sure this works on my Linux, Mac and Windows machine still. I plan on adding CI

**Comment by lukeeey** [comment]
It shouldn't effect those since i simply removed an Android check and moved it somewhere else.

**Comment by mhsjlw** [comment]
Thanks!

**Pull request merged**
